# Generated by Django 5.1.7 on 2025-04-19 05:30

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travelinfo",
            name="newComments",
            field=models.JSONField(
                default=app.models.default_json_list, verbose_name="添加用户评论"
            ),
        ),
    ]
