# Generated by Django 5.1.7 on 2025-04-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_travelinfo_newcomments"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(default="", max_length=255, verbose_name="用户名"),
                ),
                (
                    "content",
                    models.TextField(
                        default="", max_length=255, verbose_name="评论内容"
                    ),
                ),
                (
                    "creatTime",
                    models.DateField(auto_now_add=True, verbose_name="评论时间"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="travelinfo",
            name="newComments",
        ),
    ]
