# Generated by Django 5.1.7 on 2025-04-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_newcomment_remove_travelinfo_newcomments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newcomment",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="id"
            ),
        ),
    ]
