# Generated by Django 5.1.7 on 2025-04-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_newcomment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="newcomment",
            name="travelId",
            field=models.IntegerField(default=0, verbose_name="travelid"),
        ),
    ]
