# Generated by Django 5.1.7 on 2025-04-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_newcomment_travelid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newcomment",
            name="travelId",
        ),
        migrations.AddField(
            model_name="newcomment",
            name="travelTittle",
            field=models.CharField(default="", max_length=255),
        ),
    ]
