# Generated by Django 5.1.7 on 2025-04-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_newcomment_creattime"),
    ]

    operations = [
        migrations.AddField(
            model_name="newcomment",
            name="creatTime",
            field=models.TextField(default="", max_length=255, verbose_name="评论时间"),
        ),
    ]
