# Generated by Django 5.1.7 on 2025-05-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_newcomment_creattime"),
    ]

    operations = [
        migrations.AddField(
            model_name="newcomment",
            name="avatar",
            field=models.FileField(
                default="avatar/default.png", upload_to="avatar", verbose_name="头像"
            ),
        ),
    ]
