# Generated by Django 5.1.7 on 2025-05-02 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_remove_newcomment_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="newcomment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="app.user",
                verbose_name="关联用户",
            ),
        ),
    ]
