# Generated by Django 5.1.7 on 2025-05-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_newcomment_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newcomment",
            name="username",
        ),
    ]
