# Generated by Django 5.1.7 on 2025-05-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_remove_newcomment_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="newcomment",
            name="rate",
            field=models.IntegerField(default=5, max_length=255, verbose_name="评分"),
        ),
    ]
