# Generated by Django 5.1.7 on 2025-05-04 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_newcomment_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newcomment",
            name="rate",
        ),
        migrations.CreateModel(
            name="UserRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.IntegerField(default=5, verbose_name="评分")),
                (
                    "TravelSpot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="app.travelinfo",
                        verbose_name="景区",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="app.user",
                        verbose_name="用户",
                    ),
                ),
            ],
        ),
    ]
