# Generated by Django 5.1.7 on 2025-05-04 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_remove_newcomment_rate_userrating"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userrating",
            unique_together={("user", "TravelSpot")},
        ),
    ]
